[build]
target = "x86_64-unknown-linux-gnu"

[profile.release]
debug = true

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "code-model=kernel",
    "-C", "linker=ld.lld",
    "-C", "relocation-model=static",
    "-C", "link-args=--no-eh-frame-hdr --image-base 0xFFFFFFFFCAFE0000",
    "-C", "panic=abort",
    "-C", "force-frame-pointers=no",
]
