[package]
name = "shared_data"
version = "0.1.0"
edition = "2024"

[dependencies]
serial = { path = "../serial" }
spinlock = { path = "../spinlock" }
rangeset = { path = "../rangeset" }
elf_parser = { path = "../elf_parser"}
page_table = { path = "../page_table" }
